import assert from "node:assert/strict";
import test, { afterEach } from "node:test";
import JSZip from "jszip";
import { applyTrackedEdits } from "../docxTrackedChanges";
import { buildSystemPrompt } from "../chatTools";
import {
  NEUTRAL_TRACKED_CHANGE_AUTHOR,
  OUTBOUND_ATTRIBUTION_PHRASES,
  OUTBOUND_ATTRIBUTION_RULE,
  isSafeCompanyAuthor,
  resolveTrackedChangeAuthor,
  scrubOutboundAttribution,
  scrubOutboundDocxBytes,
  trackedChangeAuthorForUser,
} from "../outboundAttribution";

const originalEnv = process.env.TRACKED_CHANGE_AUTHOR;

afterEach(() => {
  if (originalEnv === undefined) delete process.env.TRACKED_CHANGE_AUTHOR;
  else process.env.TRACKED_CHANGE_AUTHOR = originalEnv;
});

test("tracked-change author prefers each tenant organisation, then env, then Author", () => {
  process.env.TRACKED_CHANGE_AUTHOR = "Amavita Research";
  assert.equal(
    resolveTrackedChangeAuthor({ organisation: "bioaccess" }),
    "bioaccess",
  );
  assert.equal(
    resolveTrackedChangeAuthor({ organisation: "Amavita Practice" }),
    "Amavita Practice",
  );
  assert.equal(
    resolveTrackedChangeAuthor({ organisation: "  Amavita Sciences™  " }),
    "Amavita Sciences™",
  );
  assert.equal(
    resolveTrackedChangeAuthor({ organisation: "bioaccess®" }),
    "bioaccess®",
  );

  assert.equal(
    resolveTrackedChangeAuthor({ organisation: null }),
    "Amavita Research",
  );
  assert.equal(
    resolveTrackedChangeAuthor({ organisation: "Mike" }),
    "Amavita Research",
  );
  assert.equal(
    resolveTrackedChangeAuthor({ organisation: "AI legal assistant" }),
    "Amavita Research",
  );

  process.env.TRACKED_CHANGE_AUTHOR = "Legal AI";
  assert.equal(
    resolveTrackedChangeAuthor({ organisation: "Mike" }),
    NEUTRAL_TRACKED_CHANGE_AUTHOR,
  );
  delete process.env.TRACKED_CHANGE_AUTHOR;
  assert.equal(
    resolveTrackedChangeAuthor({ organisation: "   " }),
    NEUTRAL_TRACKED_CHANGE_AUTHOR,
  );
  assert.equal(NEUTRAL_TRACKED_CHANGE_AUTHOR, "Author");
  assert.equal(isSafeCompanyAuthor("Mike"), false);
  assert.equal(isSafeCompanyAuthor("Amavita Research"), true);
});

test("profile organisation is the per-tenant company voice", async () => {
  process.env.TRACKED_CHANGE_AUTHOR = "Fallback Co";
  const db = (organisation: string | null) => ({
    from(table: string) {
      assert.equal(table, "user_profiles");
      return {
        select() {
          return {
            eq() {
              return {
                maybeSingle: async () => ({
                  data: { organisation },
                  error: null,
                }),
              };
            },
          };
        },
      };
    },
  });

  assert.equal(
    await trackedChangeAuthorForUser(db("bioaccess"), "user-1"),
    "bioaccess",
  );
  assert.equal(
    await trackedChangeAuthorForUser(db("Mike"), "user-1"),
    "Fallback Co",
  );
  assert.equal(
    await trackedChangeAuthorForUser(db(null), "user-1"),
    "Fallback Co",
  );
});

test("scrub removes known disclosure phrases and leaves ordinary Mike/AI prose", () => {
  const leaked =
    "This cover memo was prepared with the assistance of Mike, an AI legal assistant.";
  const scrubbed = scrubOutboundAttribution(leaked);
  assert.equal(/mike|ai legal assistant|prepared with the assistance/i.test(scrubbed), false);
  assert.match(scrubbed, /cover memo/i);

  assert.equal(
    scrubOutboundAttribution("PREPARED WITH THE ASSISTANCE OF MIKE"),
    "",
  );
  assert.equal(
    scrubOutboundAttribution("The schedule was generated by AI."),
    "The schedule was.",
  );
  assert.equal(
    scrubOutboundAttribution("Drafted by an AI for internal use."),
    "for internal use.",
  );

  const ordinary =
    "Mike Smith shall review the AI vendor clause. Michael is not a tool.";
  assert.equal(scrubOutboundAttribution(ordinary), ordinary);
  assert.equal(scrubOutboundAttribution("No disclosure here."), "No disclosure here.");

  for (const phrase of OUTBOUND_ATTRIBUTION_PHRASES) {
    const hit = scrubOutboundAttribution(`Note: ${phrase}.`);
    assert.equal(hit.toLowerCase().includes(phrase), false, phrase);
  }
});

test("docx export scrub strips disclosure text and keeps a human author name", async () => {
  const zip = new JSZip();
  zip.file(
    "word/document.xml",
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    <w:p>
      <w:r><w:t>Prepared with the assistance of Mike, an AI legal assistant.</w:t></w:r>
    </w:p>
    <w:p>
      <w:ins w:id="1" w:author="Mike Smith" w:date="2026-09-23T00:00:00Z">
        <w:r><w:t>Site shall maintain insurance.</w:t></w:r>
      </w:ins>
    </w:p>
  </w:body>
</w:document>`,
  );
  zip.file(
    "word/comments.xml",
    `<w:comments xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:comment w:author="Mike Smith"><w:p><w:r><w:t>This comment was generated by AI.</w:t></w:r></w:p></w:comment></w:comments>`,
  );
  const input = Buffer.from(await zip.generateAsync({ type: "nodebuffer" }));
  const output = await scrubOutboundDocxBytes(input);
  const outZip = await JSZip.loadAsync(output);
  const documentXml = await outZip.file("word/document.xml")!.async("string");
  const commentsXml = await outZip.file("word/comments.xml")!.async("string");
  assert.equal(/ai legal assistant/i.test(documentXml), false);
  assert.equal(/prepared with the assistance of mike/i.test(documentXml), false);
  assert.match(documentXml, /w:author="Mike Smith"/);
  assert.match(documentXml, /Site shall maintain insurance/);
  assert.equal(/generated by ai/i.test(commentsXml), false);
  assert.match(commentsXml, /w:author="Mike Smith"/);
});

async function docxWithText(text: string): Promise<Buffer> {
  const zip = new JSZip();
  zip.file(
    "word/document.xml",
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    <w:p><w:r><w:t xml:space="preserve">${text}</w:t></w:r></w:p>
  </w:body>
</w:document>`,
  );
  return Buffer.from(await zip.generateAsync({ type: "nodebuffer" }));
}

async function documentXml(bytes: Buffer): Promise<string> {
  const zip = await JSZip.loadAsync(bytes);
  const file = zip.file("word/document.xml");
  assert.ok(file);
  return file.async("string");
}

test("applyTrackedEdits never writes Mike and uses the resolved company author", async () => {
  delete process.env.TRACKED_CHANGE_AUTHOR;
  const bytes = await docxWithText("Hello world");
  const omitted = await applyTrackedEdits(bytes, [
    {
      find: "world",
      replace: "there",
      context_before: "Hello ",
      context_after: "",
    },
  ]);
  assert.equal(omitted.errors.length, 0);
  const omittedXml = await documentXml(omitted.bytes);
  assert.match(omittedXml, /w:author="Author"/);
  assert.equal(/w:author="Mike"/.test(omittedXml), false);

  const rejected = await applyTrackedEdits(
    bytes,
    [
      {
        find: "world",
        replace: "prepared with the assistance of Mike",
        context_before: "Hello ",
        context_after: "",
      },
    ],
    { author: "Mike" },
  );
  const rejectedXml = await documentXml(rejected.bytes);
  assert.equal(/w:author="Mike"/.test(rejectedXml), false);
  assert.match(rejectedXml, /w:author="Author"/);
  assert.equal(/prepared with the assistance of mike/i.test(rejectedXml), false);

  const company = await applyTrackedEdits(
    bytes,
    [
      {
        find: "world",
        replace: "there",
        context_before: "Hello ",
        context_after: "",
      },
    ],
    { author: "Amavita Practice" },
  );
  assert.match(await documentXml(company.bytes), /w:author="Amavita Practice"/);
});

test("chat and council-facing system prompts carry the global attribution ban", () => {
  const prompt = buildSystemPrompt(false);
  assert.match(prompt, /You are Mike/);
  assert.match(prompt, /NEVER/);
  assert.match(prompt, /prepared with the assistance of Mike/);
  assert.match(prompt, /every organisation and tenant/);
  assert.equal(prompt.includes(OUTBOUND_ATTRIBUTION_RULE), true);
  assert.equal(/Amavita-only|feature flag/i.test(OUTBOUND_ATTRIBUTION_RULE), false);
});
