-- Migration date: 2026-09-23
--
-- user_profiles.organisation is the per-account company voice for Word
-- tracked-change authors (bioaccess, Amavita Research, Amavita Practice,
-- Amavita Sciences, and any other Mike account). There is no tenant table.
--
-- This migration does not invent or overwrite a real company name.
-- It only clears values that are banned Mike/AI author labels so they
-- cannot be written into w:author. NULL stays NULL. The application then
-- uses TRACKED_CHANGE_AUTHOR when that value is a safe company name,
-- otherwise the neutral fallback "Author". Neither path emits Mike or AI.
--
-- To backfill a company name for accounts that are still empty, confirm
-- the name with the account owner and run a reviewed update that touches
-- only NULL rows, for example:
--
--   update public.user_profiles
--   set organisation = 'bioaccess', updated_at = now()
--   where user_id = '<uuid>'
--     and organisation is null;
--
-- Or use: npx tsx src/scripts/bootstrapOrganisation.ts --list-missing
--         npx tsx src/scripts/bootstrapOrganisation.ts --user-id <uuid> --organisation "bioaccess"
-- The script refuses Mike/AI labels and will not replace a safe name
-- unless --force is passed.

comment on column public.user_profiles.organisation is
  'Per-account company voice for Word tracked changes and exports. Not a Mike/AI label. Empty falls back to TRACKED_CHANGE_AUTHOR, then Author.';

update public.user_profiles
set organisation = null,
    updated_at = now()
where organisation is not null
  and (
    lower(regexp_replace(btrim(organisation), '\s+', ' ', 'g')) in (
      'mike',
      'ai',
      'legal ai',
      'ai legal assistant',
      'an ai legal assistant',
      'legal assistant',
      'assistant',
      'chatgpt',
      'claude',
      'grok',
      'fugu',
      'openai',
      'anthropic',
      'generated by ai'
    )
    or lower(regexp_replace(btrim(organisation), '\s+', ' ', 'g')) ~ '\mai\M'
    or (
      lower(regexp_replace(btrim(organisation), '\s+', ' ', 'g')) ~ '\mmike\M'
      and lower(regexp_replace(btrim(organisation), '\s+', ' ', 'g')) ~ '\m(ai|assistant|legal|generated)\M'
    )
  );
