/**
 * Sponsor-facing Word, redlines, comments, emails, and other exports must
 * never attribute the work to Mike or to an AI tool.
 *
 * The chat persona can still be Mike. This module only governs what is
 * written into outbound documents and the Word author on tracked changes
 * we create.
 *
 * Author resolution (first safe value wins), for every tenant:
 * 1. The acting user's organisation (`user_profiles.organisation`), which
 *    is the company name collected at signup and on the account page.
 *    There is no separate tenant table; this field is the per-account
 *    company voice (bioaccess, Amavita Research, Amavita Practice, …).
 * 2. `TRACKED_CHANGE_AUTHOR` when the organisation is missing or is itself
 *    a banned label.
 * 3. The neutral fallback "Author".
 *
 * "Mike", "AI", "Legal AI", and similar labels are never used, even if
 * they are stored as the organisation or set in the environment.
 */

import JSZip from "jszip";

export const NEUTRAL_TRACKED_CHANGE_AUTHOR = "Author";

/** Exact Word-author labels that must never be written. */
const BANNED_AUTHOR_LABELS = new Set([
  "mike",
  "ai",
  "legal ai",
  "ai legal assistant",
  "an ai legal assistant",
  "legal assistant",
  "assistant",
  "chatgpt",
  "claude",
  "grok",
  "fugu",
  "openai",
  "anthropic",
  "generated by ai",
]);

/**
 * Known disclosure phrases stripped from outbound document text.
 * Matched case-insensitively as whole phrases. Bare "Mike" or "AI"
 * inside ordinary legal prose is left alone.
 */
export const OUTBOUND_ATTRIBUTION_PHRASES = [
  "prepared with the assistance of mike, an ai legal assistant",
  "prepared with the assistance of mike",
  "prepared with the assistance of an ai legal assistant",
  "prepared with the assistance of an ai",
  "prepared with the assistance of ai",
  "with the assistance of mike, an ai legal assistant",
  "with the assistance of mike",
  "with the assistance of an ai legal assistant",
  "with the assistance of an ai",
  "with the assistance of ai",
  "mike, an ai legal assistant",
  "ai legal assistant",
  "generated by an ai",
  "generated by ai",
  "generated by mike",
  "assisted by an ai",
  "assisted by ai",
  "assisted by mike",
  "drafted by an ai",
  "drafted by ai",
  "drafted by mike",
  "written by an ai",
  "written by ai",
  "written by mike",
] as const;

const ATTRIBUTION_PATTERNS = OUTBOUND_ATTRIBUTION_PHRASES.map((phrase) => {
  const body = phrase
    .replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
    .replace(/ /g, "\\s+");
  return new RegExp(`\\b${body}\\b`, "gi");
});

/**
 * Appended to every drafting system prompt. Internal chat may still
 * identify as Mike; this bans that identity from counterparty-facing text.
 * It is a global product default for every tenant.
 */
export const OUTBOUND_ATTRIBUTION_RULE = `COUNTERPARTY-FACING OUTPUTS — NEVER ATTRIBUTE WORK TO MIKE OR AI:
This rule is a product default for every organisation and tenant. It is not optional and it is not limited to any one client.
Cover memos, redlines, comments, emails, Word documents, and any other text that may be sent to a sponsor, site, counterparty, or other external reader must be written in a human company voice only.
NEVER write "prepared with the assistance of Mike", "AI legal assistant", "generated by AI", "assisted by AI", "assisted by Mike", "drafted by AI", "drafted by Mike", "written by AI", "with the assistance of an AI", or any statement that the work was produced, assisted, drafted, or generated by Mike, an AI, a model, or a software tool.
Do not name Mike, and do not describe this system as an AI, in those outputs. The chat name Mike is internal only and must not appear in documents, exports, or cover text.
Omit the disclosure entirely. Do not replace it with a note that AI assistance was withheld or that a tool was used.`;

export function isBannedTrackedChangeAuthor(value: string): boolean {
  const normalized = value.trim().toLowerCase().replace(/\s+/g, " ");
  if (!normalized) return false;
  if (BANNED_AUTHOR_LABELS.has(normalized)) return true;
  if (/\bai\b/.test(normalized)) return true;
  if (/\bmike\b/.test(normalized) && /\b(ai|assistant|legal|generated)\b/.test(normalized)) {
    return true;
  }
  return false;
}

export function isSafeCompanyAuthor(
  value: string | null | undefined,
): value is string {
  if (typeof value !== "string") return false;
  const trimmed = value.trim();
  if (!trimmed || trimmed.length > 120) return false;
  if (/[\r\n\u0000]/.test(trimmed)) return false;
  if (isBannedTrackedChangeAuthor(trimmed)) return false;
  return true;
}

/**
 * Resolve the Word tracked-change author for one account.
 * Pass `envAuthor: undefined` only when the property is omitted to read
 * `TRACKED_CHANGE_AUTHOR`. Pass `envAuthor: null` to ignore the environment.
 */
export function resolveTrackedChangeAuthor(input?: {
  organisation?: string | null;
  envAuthor?: string | null;
}): string {
  const env =
    input && "envAuthor" in input
      ? input.envAuthor
      : process.env.TRACKED_CHANGE_AUTHOR;
  for (const candidate of [input?.organisation, env]) {
    if (isSafeCompanyAuthor(candidate)) return candidate.trim();
  }
  return NEUTRAL_TRACKED_CHANGE_AUTHOR;
}

/**
 * Company voice for the user who is producing a redline or export.
 * Lookup failure falls through to the env override, then "Author".
 * `db` is the server Supabase client; the chain is typed loosely so this
 * helper does not depend on generated table types.
 */
export async function trackedChangeAuthorForUser(
  db: { from: (table: string) => any },
  userId: string,
): Promise<string> {
  try {
    const { data, error } = await db
      .from("user_profiles")
      .select("organisation")
      .eq("user_id", userId)
      .maybeSingle();
    if (error) return resolveTrackedChangeAuthor();
    const organisation =
      data && typeof data.organisation === "string" ? data.organisation : null;
    return resolveTrackedChangeAuthor({ organisation });
  } catch {
    return resolveTrackedChangeAuthor();
  }
}

function tidyScrubbed(text: string): string {
  return text
    .replace(/[ \t]{2,}/g, " ")
    .replace(/[ \t]+([,.;:!?])/g, "$1")
    .replace(/\(\s*\)/g, "")
    .replace(/[ \t]+$/gm, "")
    .replace(/^[ \t]+/gm, "");
}

/** Strip known AI/Mike disclosure phrases. Unrelated text is unchanged. */
export function scrubOutboundAttribution(text: string): string {
  if (!text) return text;
  let out = text;
  for (const pattern of ATTRIBUTION_PATTERNS) {
    pattern.lastIndex = 0;
    out = out.replace(pattern, "");
  }
  if (out === text) return text;
  const tidied = tidyScrubbed(out);
  if (!/[\p{L}\p{N}]/u.test(tidied)) return "";
  return tidied;
}

function decodeXml(value: string): string {
  return value
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, "&");
}

function encodeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function scrubXmlTextNodes(xml: string): string {
  return xml.replace(/>([^<]+)</g, (full, raw: string) => {
    const decoded = decodeXml(raw);
    const scrubbed = scrubOutboundAttribution(decoded);
    if (scrubbed === decoded) return full;
    return `>${encodeXml(scrubbed)}<`;
  });
}

function shouldScrubDocxPart(path: string): boolean {
  const normalized = path.replace(/\\/g, "/");
  return /^word\/(?:document|comments|footnotes|endnotes|header\d*|footer\d*)\.xml$/i.test(
    normalized,
  );
}

/**
 * Remove known disclosure phrases from text in a .docx package.
 * Author attributes are left unchanged so a reviewer's own name is not
 * rewritten. Returns the original buffer when the package is not a docx
 * or when nothing matched.
 */
export async function scrubOutboundDocxBytes(bytes: Buffer): Promise<Buffer> {
  let zip: JSZip;
  try {
    zip = await JSZip.loadAsync(bytes);
  } catch {
    return bytes;
  }
  const documentPart =
    zip.file("word/document.xml") ?? zip.file("word\\document.xml");
  if (!documentPart) return bytes;

  let changed = false;
  for (const name of Object.keys(zip.files)) {
    if (zip.files[name]?.dir) continue;
    if (!shouldScrubDocxPart(name)) continue;
    const file = zip.file(name);
    if (!file) continue;
    const xml = await file.async("string");
    const next = scrubXmlTextNodes(xml);
    if (next !== xml) {
      zip.file(name, next);
      changed = true;
    }
  }
  if (!changed) return bytes;
  const out = await zip.generateAsync({ type: "nodebuffer" });
  return Buffer.from(out);
}
